spring:
  main:
    allow-bean-definition-overriding: true
    #mysql设置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/
    username: your username
    password: your passowrd
  #jpa设置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
