spring:
  main:
    allow-bean-definition-overriding: true
    #mysql设置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/
    username: your username
    password: your password
  #jpa设置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  #thymeleaf设置
  thymeleaf:
    cache: true
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: html

site:
  url: rkroom.com
  port: 8080
  title: 菜鸟学堂